apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-kube-deployment
  name: hello-kube-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 3000
  selector:
    app: hello-kube-deployment
